{
 "title": "GitHub Repository Stats",
 "tags": [ "github-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "user", "query": "label_values(user)" },
   {
    "name": "repo",
    "query": "label_values(github_repo_open_issues{user=\"$user\"}, repo)"
   }
  ]
 },
 "panels": [
  {
   "title": "Open Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "github_repo_open_issues{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Open Pull Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "github_repo_pull_request_count{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "github_repo_forks{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "github_repo_stars{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "github_repo_watchers{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Repository Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "github_repo_size_kb{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "github_repo_open_issues{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Open Pull Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "github_repo_pull_request_count{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "github_repo_forks{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "github_repo_stars{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "github_repo_watchers{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  },
  {
   "title": "Repository Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "github_repo_size_kb{user=~\"$user\",repo=~\"$repo\"}"
    }
   ]
  }
 ]
}